### ISSUE TITLE
左侧tree的层级错误

### ISSUE THREAD

**Issue by the-eric-kwok** [ic005k/QtiASL#1]
![image](https://user-images.githubusercontent.com/16463312/93559900-62300d80-f9b3-11ea-9746-e76e88247cf3.png)
实际上UPBS到CBSS这四个Method都是在BAT0这个Scope下的

[SSDT-BatteryFix-bc015tx.dsl.zip](https://github.com/ic005k/QtiASL/files/5243607/SSDT-BatteryFix-bc015tx.dsl.zip)

**Comment by ic005k** [comment]
哦，明白你说的意思。这个是ssdt的作者写法习惯问题，实际上按 "Scope(\_SB.BAT0) {" 这种写法，一点都没问题，编译也不会出错，也是我们写代码的常用风格之一，但目前QtiASL没有解析Scope、Device、Method后面紧跟"{"的这种写法。将"{"回车另起一行，就没问题了：
Scope(\_SB.BAT0) 
	{   ...

后面的版本会考虑解析这种写法，感谢你的反馈。

**Comment by the-eric-kwok** [comment]
Fixed in https://github.com/ic005k/QtiASL/releases/tag/V1.0.10
