### ISSUE TITLE
最近两个版本，在搜索框里面一输入就crash

### ISSUE THREAD

**Issue by kavern1128** [ic005k/QtiASL#10]
在win10下面，最近的两个版本，在搜索框里面一输入，软件就失去响应崩溃，麻烦看看什么问题，谢谢

**Comment by ic005k** [comment]
问题已修复，请重新下载win版本：https://github.com/ic005k/QtiASL/releases/download/1.0.48/QtiASL-win.7z
感谢反馈

**Comment by kavern1128** [comment]
可以了，非常感谢
