### ISSUE TITLE
QtiASL doesn't support DSDT patch

### ISSUE THREAD

**Issue by b-uild** [ic005k/QtiASL#11]
in some editors, they support patching DSDT by using coded txt, but this editor doesn't support this feature.

**Comment by ic005k** [comment]
Yes, the dsdt patch is not supported. Because nowadays it is all patched via ssdt and dsdt patching is obsolete. So there is no consideration for this feature, thanks for the feedback.

**Comment by b-uild** [comment]
Ok, understandable. Thanks for fast reply!
