### ISSUE TITLE
希望添加打补丁功能。

### ISSUE THREAD

**Issue by lingering2019** [ic005k/QtiASL#12]
例如添加这样的补丁。
# Fix the LPC Device
into method label _DSM parent_label LPCB remove_entry;
into device label LPCB insert begin
Method (_DSM, 4, NotSerialized)\n
{\n
	Store (Package (0x02) {\n
		"compatible", Buffer () {"pci8086,1c45"}\n
	}, Local0)\n
	DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))\n
	Return (Local0)\n
}
end;

**Comment by ic005k** [comment]
这个功能，之前也有人提到过。估计不会重点考虑，因为这种对dsdt打补丁的方式几乎已经淘汰了，现在都是通过ssdt来修正系统dsdt所存在的问题。
同时QtiASL的定位将是一个面向现代的通用型的ASL语言IDE，它不仅仅为黑苹果服务。

**Comment by lingering2019** [comment]
懂了。
