### ISSUE TITLE
Remove redundant files: patchmatic-old and bearer ?

### ISSUE THREAD

**Issue by mackonsti** [ic005k/QtiASL#13]
Hello @ic005k and thank you very much for creating and offering your great tool, it is very appreciated.

I would like to report a couple of simple issues for the next maintenance release:

a) inside MacOS folder there is a file that seems to not be used that was left inside your ZIP release:

`patchmatic-old`

Perhaps consider removing it? Unless it's used? If you are using perhaps consider renaming it to:

`patchmatic-legacy`

for example to avoid thinking it's left inside by error 😄 

b) I have discovered that the Qt library `bearer` is causing problems.

Please refer to https://github.com/nextcloud/desktop/issues/2944 where after a lot of effort, myself and some people found out this library is flooding the system log with errors (without reason) on _some_ Macs.

If you are not using `bearer` can I suggest you do **not** package it (not include it) in your application folders?

c) Finally, there is **no** "Quit" menu appearing in the top menus and specifically "QtiASL" like all other Mac applications, there is no "clean" way to quit the application except closing a window.

Perhaps consider also adding this simple but standard menu item? Even **Command+Q** keyboard shortcut does not work.

Many thanks. Xie Xie

**Comment by ic005k** [comment]
Ok, you are really a meticulous person, thank you very much for your feedback, I will improve these contents.

**Comment by mackonsti** [comment]
It's just the recent experience of mine and my desire to contribute to this nice program! Thank you for taking these into consideration. I also wanted to report that CMD+W doesn't close the tabs or windows, just FYI. As I am a long-time power user, I use the keyboard a lot (and its shortcuts)... Thank you.

**Comment by ic005k** [comment]
> that CMD+W doesn't close the tabs or windows
Documented, these will be added or improved in the next version.

**Comment by mackonsti** [comment]
Thank you for releasing https://github.com/ic005k/QtiASL/releases/tag/1.0.54 so fast @ic005k

I can close tabs with Cmd+W which is great, but cannot quit the application completely with Cmd+Q nor is there a menu "Quit" in the menubar. Just for your information... I am just referring to your release note:

> New: Quit and Close tab menu and shortcut keys

Also, a small suggestion for next release: it seems that some _unnecessary_ MacOS Finder attributes files were stored in your ZIP release file, which appear when unzipped as `._xyz` e.g. in **MacOS** folder there is a file `._patchmatic` and in **Resources** folder there are files like `._Icon.icns` and `._dsl.icns` etc.

If you can, before zipping the Release, to clean up any extended attributes of the main application:
`xattr -rc QtiASL.app`

I do that in most applications I download so that Finder doesn't complain about this file being "damaged" (for other tools) etc. etc. etc. Just a small friendly advice!

Thanks again for your feedback.

**Comment by ic005k** [comment]
> with Cmd+Q nor is there a menu "Quit" in the menubar

Actually on my side, it has been working fine, I am currently using Big Sur 11.2.3 , I'll go back and see if it works on another 10.15 machine. Thanks for the feedback, I'll keep an eye on this issue.

**Comment by ic005k** [comment]
> Also, a small suggestion for next release: it seems that some _unnecessary_ MacOS Finder attributes files were stored in your ZIP release file, which appear when unzipped as `._xyz` e.g. in **MacOS** folder there is a file `._patchmatic` and in **Resources** folder there are files like `._Icon.icns` and `._dsl.icns` etc.

Okay, I'll keep an eye on this phenomenon. Maybe I need to test on other machines to see if this phenomenon exists, thanks for the feedback.

**Comment by ic005k** [comment]
By the way, I am using this software for packaging: https://www.keka.io/en/ , is there a relationship with this packaging software? I've never noticed this phenomenon before, but I'll find the reason anyway.

**Comment by mackonsti** [comment]
> Actually on my side, it has been working fine, I am currently using Big Sur 11.2.3 , I'll go back and see if it works on another 10.15 machine.

Do you get a Quit menu in the top menu bar? I am on Catalina indeed, I do not get such menu, and neither Cmd+Q works to be honest. Thanks however for your response.

> By the way, I am using this software for packaging: https://www.keka.io/en/

I am also decompressing with Keka @ic005k so perhaps you can add the option in (your) Keka to "Exclude Mac resource forks" which are these extended attributes I talk about, when you compress. Thank you.

**Comment by ic005k** [comment]
> "Exclude Mac resource forks"

That's probably the problem, I really don't have that option turned on. Thank you very much.

**Comment by ic005k** [comment]
> I am on Catalina indeed

I will test and fix this issue.

**Comment by mackonsti** [comment]
Thank you for the latest release @ic005k you can now **close** this ticket!
One thing you could consider is when you change font size, to also increase the device-tree window (left side) and not just the ACPI code window 😄 
Many thanks for your kind additions. I may report back an issue if found.
Take care, stay safe.

**Comment by ic005k** [comment]
> when you change font size, to also increase the device-tree window (left side) and not just the ACPI code window

Ok, I will tweak it in the next version, thanks.
