### ISSUE TITLE
能否增加该工具的使用说明。简单点即可。谢谢！

### ISSUE THREAD

**Issue by liuyunli** [ic005k/QtiASL#15]

**Comment by ic005k** [comment]
软件本身好像也没什么要说明的，软件的使用是非常简单的，难点是dsdt的相关知识，这是最难的地方。
对于软件，你拖拽一个dsdt文件到窗口就可以进行编辑了。
要获得系统的dsdt文件，选择“编辑”菜单中的“获取ACPI表”即可。
整个过程很简单，难点在于如何分析dsdt，这个就需要你查阅相关ACPI的资料了。

**Comment by ic005k** [comment]
界面上还有6个按钮，鼠标移到按钮上都有功能说明，一看就明白了，很简单的。

**Comment by ic005k** [comment]
再一个就是dsdt+ssdt反编译，也很简单
你选一个dsdt，然后在下面再选一些ssdt，即可结合ssdt里面的内容重新生成一个新的dsdt

**Comment by ic005k** [comment]
还有就是软件自动更新，要是下载不动的话，就在“帮助”菜单中选一个镜像服务器试试。

**Comment by ic005k** [comment]
软件本身就这些东西，它是分析dsdt非常便利的工具，非常高效易用。
对于工具本身，有任何问题或建议，可随时留言。

**Comment by ic005k** [comment]
还有个特点就是跨平台，在windows下也可以提取和分析dsdt，功能和mac版本一样。

**Comment by liuyunli** [comment]
邮箱有问题，没及时看到消息。 你提到的这些我没有什么疑问，我的疑问是修改后如何重新编译并load进系统。这种load是否会对系统造成破坏？我目前只有一台电脑，没敢尝试。谢谢！

**Comment by ic005k** [comment]
修改后直接点击编译按钮就可以重新编译了（编辑菜单里面也有编译菜单）。
简单地讲，将编译之后的aml文件放入诸如OC的acpi目录并在配置文件里面加载它就可以注入了，当然如果注入了不正确的ssdt或dsdt，肯定会对系统有些影响的，最直观的表现就是可能无法进入系统。
修改dsdt或者是ssdt的方法，更详尽的内容可在网上搜下，非常之多，有很多用户分享了这些内容。

**Comment by wan-kenny** [comment]
> 修改后直接点击编译按钮就可以重新编译了（编辑菜单里面也有编译菜单）。 简单地讲，将编译之后的aml文件放入诸如OC的acpi目录并在配置文件里面加载它就可以注入了，当然如果注入了不正确的ssdt或dsdt，肯定会对系统有些影响的，最直观的表现就是可能无法进入系统。 修改dsdt或者是ssdt的方法，更详尽的内容可在网上搜下，非常之多，有很多用户分享了这些内容。Xiasl.exe +aml文件  或者 iasl.exe+aml文件 都不能写入文件

具体怎么写入windows 平台下的acpi呢？我一直没找到解决方案，

**Comment by ic005k** [comment]
写入Windows通常是靠OC来完成的，你只需通过OC来引导Windows，它即可注入你既定的aml文件内容。
我们这里讨论的是OC引导相关内容，我不知道你所指的是不是这些。

**Comment by ic005k** [comment]
如果你是一个dsdt的开发者或者尝试开发dsdt，那么注入和测试的方法就比较复杂和专业了，一两句说不清楚，具体可以参考ACPI的相关文档，Xiasl的帮助菜单里面有相关的链接。

**Comment by liuyunli** [comment]
我目前从事的是WIN的驱动开发, OC 我刚查了下应该是macos引导windows的，与我的需求可能有区别

**Comment by ic005k** [comment]
哦，明白，你是一个专业的尝试dsdt的开发者，那就好办了，你只需找主板厂家索取相关的资料，主板厂家一般都有公版的dsdt给你，供你参考，并同时提供测试相关的整套工具。

**Comment by wan-kenny** [comment]
可以了,我的工具使用错了.已经完美解决我的问题了

**Comment by liuyunli** [comment]
主板厂商会给吗？ 我们刚开始搞这个，不太清楚，能否再分享点信息？而且我们用的是SPI I2C等需要定制的接口，普通主板可能无法提供。

**Comment by ic005k** [comment]
如果涉及到定制，那可能需要自己造轮子了。其实我写这个dsdt的开发IDE是为了分析和修改系统的dsdt，以适用macOS的系统环境，我并没有从头开发dsdt的工作经验，所以更详尽的细节内容，我没法与你分享。
但是，如果你在使用Xiasl这个IDE的过程中，有什么需要改进或任何问题或建议，可随时留言，我会不断改进这个工具的。

**Comment by liuyunli** [comment]
好的。感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月11日(星期二) 中午11:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ic005k/QtiASL] 能否增加该工具的使用说明。简单点即可。谢谢！ (Issue #15)





 
如果涉及到定制，那可能需要自己造轮子了。其实我写这个dsdt的开发IDE是为了分析和修改系统的dsdt，以适用macOS的系统环境，我并没有从头开发dsdt的工作经验，所以更详尽的细节内容，我没法与你分享。
 但是，如果你在使用Xiasl这个IDE的过程中，有什么需要改进或任何问题或建议，可随时留言，我会不断改进这个工具的。
