### ISSUE TITLE
A new untitled.dsl tab added at each boot

### ISSUE THREAD

**Issue by perez987** [ic005k/QtiASL#19]
First of all, thank you very much for your work, Xiasl is an excellent app. Very useful.
But I want to propose something. Every time Xiasl starts, it creates a new untitled.dsl tab or open a file. All the recent files plus an untitled tab for each boot are accumulated in the form of tabs.
It is possible to modify this behaviour so that Xiasl, by default, starts with a single untitled.dsl tsb or at least with only the current or the last open file?
Regards, Emilio.

**Comment by ic005k** [comment]
Received. I will improve it, thanks for your attention.

**Comment by ic005k** [comment]
It has been updated, please upgrade to the latest version.
Any questions or suggestions are welcome, thank you.

**Comment by perez987** [comment]
Thank you!!! Great job.
