### ISSUE TITLE
[Feature Request] 类似于MaciASL的报错页面

### ISSUE THREAD

**Issue by the-eric-kwok** [ic005k/QtiASL#2]
我注意到目前QtiASL编译时似乎使用了 Force 参数，代码中有错误的情况下依旧会编译出成果，是否考虑增加一个代码中的错误的跳转功能呢？

**Comment by ic005k** [comment]
是的，目前是采用了Force参数，初衷是为了提高编译的成功率。目前如果Force编译还是出错，则会出现出错的代码跳转，比如你在任意地方写个：
Device()
{

}

编译时则会出现错误，此时会跳转到错误行，并用"红点"进行标记，顶栏 <<<< 和  >>>>按钮可进行错误行的前后追踪。

不过，这一块的业务逻辑，确实需要重新思考并优化一下，感谢你的反馈。

**Comment by ic005k** [comment]
同时在编译信息输出的"Errors"标签页面可以看到详细的错误内容，并指出错误所在，在此处任意信息行上点击，便会定位到错误行，比如：

/Users/zh/Downloads/SSDT-BatteryFix-bc015tx.dsl    511:             If (ECAV)
Error    6084 -                                     Object does not exist                     ^         (ECAV)

这条错误信息里面，符号"^"，指出了错误所在，" Object does not exist"告诉你错误原因等等。

**Comment by the-eric-kwok** [comment]
啊原来在这，感谢解惑🙏
BTW：QtiASL的批量Tab和Shift-Tab功能是真滴好用，爱了❤️

**Comment by ic005k** [comment]
目前1.0.15版本已增加了编译参数的选项，用户可以自选择或自定义编译参数。

**Comment by the-eric-kwok** [comment]
建议在编译参数处添加参数作用的说明😄我建议是隐藏编译参数的细节，而将 -f 改为“忽略错误”，-tp 改为 “正常编译”

此外，搜索和替换框部分目前没有相关的文字说明，如果可以在文本框内放置一个提示之类的说明就更好了，比如
`QLineEdit.setPlaceholderText( const QString & )`？
类似这样的hint
![image](https://user-images.githubusercontent.com/16463312/95005205-ab28c880-0627-11eb-97e1-9e46e45db36b.png)

**Comment by ic005k** [comment]
> 
> 
> 建议在编译参数处添加参数作用的说明😄我建议是隐藏编译参数的细节，而将 -f 改为“忽略错误”，-tp 改为 “正常编译”
> 
> 此外，搜索和替换框部分目前没有相关的文字说明，如果可以在文本框内放置一个提示之类的说明就更好了，比如
> `QLineEdit.setPlaceholderText( const QString & )`？
> 类似这样的hint
> ![image](https://user-images.githubusercontent.com/16463312/95005205-ab28c880-0627-11eb-97e1-9e46e45db36b.png)

你说的这些功能，由于时间关系，目前在新版的软件中部分已实现。
欢迎提供更多的、任何建设性的意见，感谢你的反馈。
