### ISSUE TITLE
How to change the location of the "ACPI Tables" folder?

### ISSUE THREAD

**Issue by hoaug-tran** [ic005k/QtiASL#22]
**Is there a way to make the software create the "ACPI Folder" folder where the software is stored instead of creating it on the Desktop? thank you!**

**Comment by ic005k** [comment]
Well, the next version will change the default directory location.

**Comment by ic005k** [comment]
Also, the location of this folder is fixed and cannot be changed by Settings at this time.

**Comment by hoaug-tran** [comment]
Thank you @ic005k , I'm looking forward to it <3
