### ISSUE TITLE
[Bug] 在大规模DSDT中搜索时导致左侧树图与右侧光标位置不同步

### ISSUE THREAD

**Issue by the-eric-kwok** [ic005k/QtiASL#3]
包括搜索时和用户鼠标点击时

目前的行为是左侧树图会高亮当前Method/Device/Scope，但是不会跳转到当前位置，在DSDT中大量的方法内搜索的时候会很难找到当前所在的Method/Device/Scope，所以特此提一个建议 😊

**Comment by ic005k** [comment]
这种联动映射关系是一直存在的，包括搜索、光标移动等。你是不是在一个很大的区块里面编辑或移动光标？只有当光标跨越到另外一个Scope、Device或Method区块，左侧的条目焦点才会变化。
还有，点击左侧的条目，会定位到该条目的代码区块。

**Comment by ic005k** [comment]
同时，如果在搜索的过程中，左侧的条目焦点始终没有任何变化，说明此时光标位置所在的代码区块不属于任何Scope、Device或Method范围之内。

**Comment by the-eric-kwok** [comment]
![image](https://user-images.githubusercontent.com/16463312/93714278-23a57900-fb94-11ea-8089-170077348297.png)
那么我遇到的似乎是一个bug，主要出现在搜索之后

**Comment by ic005k** [comment]
图中的UPBI似乎没有在左边的树图中显示出来？你附上这个文件，我这边检查一下。
或者你手动刷新一下树图，看看左边能否有UPBI这个Method的条目。

**Comment by ic005k** [comment]
如果左边不存在UPBI这个条目，那么是无法在右边的代码区块内定位到它的。

**Comment by ic005k** [comment]
而且从图中提供的信息来看，UPBI上面的_BST，似乎在左边的树图中也没有排列在其上面。也就是说整个层次是紊乱的。
造成树图层次紊乱的原因，可能是：
代码层次结构出现问题，这个是主要原因。比如可能在编写或者复制粘贴代码的时候，打乱了原始代码的层次结构。

**Comment by the-eric-kwok** [comment]
[dsdt.dsl.zip](https://github.com/ic005k/QtiASL/files/5259160/dsdt.dsl.zip)
好的，文件已上传

**Comment by ic005k** [comment]
我下载了上面的文件，但问题并没有在我这边复现，我这边显示正常。
回头我再查找下，有可能出现这个现象的原因。

**Comment by the-eric-kwok** [comment]
尝试搜索一些关键字？
我这边复现概率还挺高的，遇到好几次了
尤其是大规模的DSDT容易出现

**Comment by ic005k** [comment]
新版的软件修复了一处解析错误，是不是跟你说的这个现象有关联？请下载最新的软件看看能否在你那边复现你提的这个问题。

**Comment by the-eric-kwok** [comment]
@ic005k 看起来被修复了，我先关闭issue，将来如果复现的话再reopen
现在有一个新的问题，我另外开一个issue好了
