### ISSUE TITLE
光标在Field中时树图中定位不准确？

### ISSUE THREAD

**Issue by the-eric-kwok** [ic005k/QtiASL#4]
![image](https://user-images.githubusercontent.com/16463312/98436050-10824480-2113-11eb-987f-1c824db11a98.png)
如图，当光标不在_STA中的时候树图中显示为处于_STA中。按照我的理解此时应该是在EC0中才是准确的。
[dsdt.dsl.zip](https://github.com/ic005k/QtiASL/files/5504472/dsdt.dsl.zip)

**Comment by ic005k** [comment]
目前是这样的，如果不在任何一个范围之类，程序会将左边的成员聚焦到当前光标所在位置的上一个Device或者Method。
感谢反馈，或许后面会有更好的显示方法，我将优化它。

**Comment by the-eric-kwok** [comment]
我认为应该保持准确的从属关系，如图中情况应定位到 EC0，如果光标不在 _STA 内却定位到 _STA 的话可能会造成误导😁

**Comment by ic005k** [comment]
> 我认为应该保持准确的从属关系，如图中情况应定位到 EC0，如果光标不在 _STA 内却定位到 _STA 的话可能会造成误导😁

好的，已记录。感谢建议和反馈！
