### ISSUE TITLE
文件已编辑标记不准确

### ISSUE THREAD

**Issue by the-eric-kwok** [ic005k/QtiASL#5]
<img width="216" alt="image" src="https://user-images.githubusercontent.com/16463312/99617368-30dac900-2a5a-11eb-9708-c57416f27cbb.png">
如图，编辑后左侧绿点不会变红，直到切换标签页时才会变红（看起来是需要更新状态？）

系统：macOS BigSur 11.0.1

**Comment by ic005k** [comment]
抱歉，目前确实是这样的，切换标签页的时候，编辑状态才会改变。
已记录，后面会优化，欢迎更多的建议，感谢反馈！

**Comment by the-eric-kwok** [comment]
@ic005k 似乎按撤销键撤销编辑后依然是已编辑的状态，这是个known issue吗？是否有修复的计划呢？

**Comment by ic005k** [comment]
> @ic005k 似乎按撤销键撤销编辑后依然是已编辑的状态，这是个known issue吗？是否有修复的计划呢？

目前这块没有纳入处理范围，后面会处理的。感谢反馈！
