### ISSUE TITLE
Windows下迷你视图放大镜导致程序崩溃

### ISSUE THREAD

**Issue by the-eric-kwok** [ic005k/QtiASL#9]
似乎是在启动了多个实例后会出现

**Comment by ic005k** [comment]
好的，收到并记录。感谢反馈！

**Comment by ic005k** [comment]
这个问题已修复，请下载最新的版本1.0.45。

**Comment by the-eric-kwok** [comment]
确认已修复
此外，Windows上双击打开的时候为啥会在新窗口打开啊？如果有标签页的不是应该默认在标签页中打开吗

**Comment by ic005k** [comment]
> 确认已修复
> 此外，Windows上双击打开的时候为啥会在新窗口打开啊？如果有标签页的不是应该默认在标签页中打开吗

其实这是个历史遗留问题，当时还没有实现拖拽标签页形成一个新的窗口的情况下，是为了实现多窗口打开文件（有用户需求），win下就一直沿用了这个特性，因为之前有用户说，QtiASL打开文件的途径太多了，建议保留Windows下的这个特性，如果采用单窗口，可以使用拖拽文件到软件界面打开或者通过软件内置的文件浏览器打开等等方式，所以就一直没改变这个方式。
总之，可能会先保留一段时间吧，但最终可能会和mac一样，在同一个窗口的标签页上打开。

**Comment by ic005k** [comment]
对了，拖拽文件或通过软件的文件菜单打开文件，均支持批量选择文件。这个特性好像我在软件说明中没有提到，主要也没有太多时间来写文档。
